spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/${POSTGRESQL_DATABASE}
    username: ${POSTGRESQL_USERNAME}
    password: ${POSTGRESQL_PASSWORD}}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true

# TODO: Replace with a real webhook

stripe:
  webhook-key: ${STRIPE_WEBHOOK_KEY}
  secret-key: ${STRIPE_SECRET_KEY}