spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: task-db
  datasource:
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    url: ${SONG_DB_CONNECTION_URL:jdbc:postgresql://localhost:5432/educational_system_task_db}
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect