spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  datasource:
    primary:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres?currentSchema=s1
      username: postgres
      password: password
    subscription:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/conn_details_db
      username: connect
      password: details


app:
  security:
    secret-key: secret
    token-expire: 1h
  urm:
    invite:
      expiration:
        validation: 24h
        registration: 1h
