spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_auth
    username: postgres
    password: postgres

app:
  security:
    secret-key: secret
    token-expire: 1h
