version: "3.8"

services:
  postgres:
    image: postgres:15.4
    container_name: auth-postgres
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: