# docker-compose file for test db

version: '3'
services:
  db-auth:
    image: postgres:14.1
    container_name: db-auth
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_auth
